name: Update Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab or from the API
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash that should be marked as the deployment head'
        required: true
        type: string

jobs:
  publish-deployment:
    permissions:
      contents: read
      pull-requests: write
    uses: markwhitfeld/test-deployments/.github/workflows/update-repository-ref.yml@main
    with:
      repository_name: test-service-one
      image_commit_hash: ${{ inputs.commit_hash }}
    secrets:
      deployments-repo-token: ${{ secrets.GITOPS_REPO_PAT }}  

  deploy:
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: publish-deployment
      environment:
        name: 'Enterprise Server Preview'
        url: http://www.stackblitz.com
        # url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        
        ### TESTING OUTPUTS ##
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
          
        - name: Dump inputs context
          env:
            INPUTS_CONTEXT: ${{ toJson(inputs) }}
          run: echo "$INPUTS_CONTEXT"
          
        - name: Dump job context
          env:
            JOB_CONTEXT: ${{ toJson(job) }}
          run: echo "$JOB_CONTEXT"
          
        - name: Dump steps context
          env:
            STEPS_CONTEXT: ${{ toJson(steps) }}
          run: echo "$STEPS_CONTEXT"
          
        - name: Dump runner context
          env:
            RUNNER_CONTEXT: ${{ toJson(runner) }}
          run: echo "$RUNNER_CONTEXT"
          
        - name: Dump exports
          run: export
